Feature #11914: adding state management to Group model.
Silverpeas/Silverpeas-Core pull request #1207
Opened 2022-03-17 20:31 UTC by SilverYoCha

Creating new version of SQL scripts about busCore.

Modifying GroupDAO SQL queries in order to take into account the new table fields.
Making that REMOVED state is always filtered, but not explicitly requested.

Fixing unindexation of subgroups of removed/deleted groups.

Taking into account the REMOVED State into Group synchronization.

Modifying to group page in order to wire the new remove/delete.
Adding the page to manage removed groups.

Adding the scheduler in charge of the removing of removed groups.

2022-03-31 09:17 UTC, mmoqui requested changes

2022-03-31 13:00 UTC, SilverYoCha commented on core-api/src/main/java/org/silverpeas/core/admin/user/model/Group.java
> +  GroupState getState();
Group#getState() allows to get the state value of the group and manipulates it to do some stuffs.
The other methods allows to check a specific state without coding the condition.

2022-03-31 13:00 UTC, SilverYoCha commented on core-configuration/src/main/config/properties/org/silverpeas/jobDomainPeas/multilang/jobDomainPeasBundle_de.properties
> +JDP.groupDelConfirmHelp=if checked, group and its subgroups are permanently deleted, otherwise they can be later restored
OK

2022-03-31 13:02 UTC, SilverYoCha commented on core-configuration/src/main/config/properties/org/silverpeas/jobDomainPeas/multilang/jobDomainPeasBundle_de.properties
> +JDP.groupRemoveDate=Date of the group remove
OK

2022-03-31 13:02 UTC, SilverYoCha commented on core-configuration/src/main/config/properties/org/silverpeas/jobDomainPeas/multilang/jobDomainPeasBundle_de.properties
> +JDP.groupAutomaticDeletionDate=Date of permanent deletion
OK

2022-03-31 13:03 UTC, SilverYoCha commented on core-configuration/src/main/config/properties/org/silverpeas/jobDomainPeas/multilang/jobDomainPeasBundle_en.properties
> +JDP.groupRemoveDate=Date of the group remove
OK

2022-03-31 13:03 UTC, SilverYoCha commented on core-configuration/src/main/config/properties/org/silverpeas/jobDomainPeas/multilang/jobDomainPeasBundle_en.properties
> +JDP.groupAutomaticDeletionDate=Date of permanent deletion
OK

2022-03-31 13:05 UTC, SilverYoCha commented on core-configuration/src/main/config/resources/StringTemplates/core/admin/domain/removedGroupHelp_en.st
> +At this level, it is possible to :
OK (you wanted to write ':' and not ';', that is right?)

2022-03-31 13:09 UTC, SilverYoCha commented on core-configuration/src/main/config/resources/StringTemplates/core/admin/domain/removedGroupHelp_en.st
> +<li>restore groups. Their rights to which they belonged <b>at time of their remove</b> are also restored.</li>
OK

2022-03-31 13:10 UTC, SilverYoCha commented on core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
> +        deleteProfileInst(component.getProfileInst(p).getId());
Mmm, I suddenly have a doubt. I check that right away and I come to validate this point.

2022-03-31 13:42 UTC, mmoqui commented on core-api/src/main/java/org/silverpeas/core/admin/user/model/Group.java
> +  GroupState getState();
Ok but this method doesn't seem to be used and according to the doc its handling is expected to be useless

2022-03-31 13:48 UTC, SilverYoCha commented on core-library/src/main/java/org/silverpeas/core/admin/service/DefaultAdministration.java
> +        deleteProfileInst(component.getProfileInst(p).getId());
OK, I checked again this modification.
This code is performed only into the case of space logical deletion, so it was a mistake to not delete inherited profiles too on a such treatment.
In order to clarify that, I renamed the method.

2022-03-31 14:26 UTC, mmoqui commented on core-api/src/main/java/org/silverpeas/core/admin/user/model/Group.java
> +  GroupState getState();
oki

2022-04-01 14:12 UTC, mmoqui approved these changes

2022-04-01 14:58 UTC, merged