Feature #13059
Silverpeas/Silverpeas-Core pull request #1222
Opened 2022-05-18 09:04 UTC by mmoqui

Update dependencies according to the changes in
silverpeas-dependencies-bom.

Remove dependency on jetbrains annotation lib to prefer those provided
by the JSR 305.

Merge before PR https://github.com/Silverpeas/silverpeas-dependencies-bom/pull/40

2022-05-31 09:34 UTC, SilverYoCha requested changes

2022-05-31 16:02 UTC, mmoqui commented on core-library/src/main/java/org/silverpeas/core/importexport/ical/ical4j/ICal4JICalCodec.java
> +    if(StringUtil.isDefined(this.hostInfo.getHostName())) {
No because hostInfo is never null. It set at construction time.

2022-05-31 16:07 UTC, SilverYoCha commented on core-library/src/main/java/org/silverpeas/core/importexport/ical/ical4j/ICal4JICalCodec.java
> +    if(StringUtil.isDefined(this.hostInfo.getHostName())) {
Ho yes indeed!

2022-06-01 09:11 UTC, SilverYoCha approved these changes

2022-06-01 13:49 UTC, merged