Feature 13448
Silverpeas/Silverpeas-Core pull request #1306
Opened 2023-11-20 10:07 UTC by mmoqui

* The content of the comments isn't anymore used to set the index field `TITLE` and, through it, the index field `HEADER` dedicated to the search.
* A new facet is introduced to select only the comments among the search results.

2023-11-21 09:42 UTC, mmoqui commented
Rebased and merged by hand

2023-11-21 09:43 UTC, mmoqui commented
Wrong PR closed!

2023-11-22 13:35 UTC, SilverYoCha requested changes

2023-11-23 09:30 UTC, mmoqui commented on core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexEntryKey.java
> +  private final String linkedObjectId;
In fact, in my mind, a linked object is not a container object. A group or a space are container objects. A publication is a linked object as other contributions can be linked to it.
An IndexEntryKey refers always a given Silverpeas resource into an index. So, the component identifier, the type of the resource and the unique identifier of such a resource makes a reference to this resource in Silverpeas. Such reference attributes are enough to identify uniquely a first-class resource in Silverpeas (space, app, publication, ...) but for second-class resources such as comments or attachments. Latter require to have also the unique identifier of the object to which they are linked.

2023-11-23 09:32 UTC, mmoqui commented on core-library/src/main/java/org/silverpeas/core/index/indexing/model/IndexEntryKey.java
> +  private String normalize(final String raw) {
Yes, you're right. I'm going to change that.

2023-11-23 09:37 UTC, mmoqui commented on core-services/comment/src/main/java/org/silverpeas/core/comment/service/DefaultCommentService.java
> +    User user = cmt.getCreator();
I'll check.

2023-11-23 09:42 UTC, mmoqui commented on core-war/src/main/java/org/silverpeas/web/pdc/control/PdcSearchSessionController.java
> +          String id = result.isLinked() ? result.getLinkedResourceId() : result.getId();
The code here is to satisfy the previous behavior: the 
```java
result.getId()
```
returned the identifier of the linked object (the publication or whatever). Indeed, previously the identifier of the indexed contribution (here the attachment) were set in the object type.

So the code here is to check the result refers a second-class contribution (the attachment) and, in this case, in order to have the same behavior than before, it is necessary to get the identifier of the linked object (id est publication or whatever)

2023-11-23 09:43 UTC, mmoqui commented on core-war/src/main/java/org/silverpeas/web/pdc/control/PdcSearchSessionController.java
> +      st.wordChars('\u0000', 'ÿ');
Yes with Java 11

2023-11-23 10:10 UTC, mmoqui commented on core-services/comment/src/main/java/org/silverpeas/core/comment/service/DefaultCommentService.java
> +    User user = cmt.getCreator();
I checked.

The content matching the search is returned, whatever the language in which it is written. In the case of the comments, their title in the results are in the language of the author of the comment. So, a French user behind a search will see the comments authored by an English user in the result page with their title in English.

In the other side, if the comments are written in English and the user asks for a text written in French, he shouldn't see the English comments unless there are similar words in both language.

2023-11-28 13:32 UTC, SilverYoCha commented on core-services/comment/src/main/java/org/silverpeas/core/comment/service/DefaultCommentService.java
> +    User user = cmt.getCreator();
OK. I'll also be looking at that when I do my tests.

2023-11-30 13:24 UTC, merged